image: maven:3.9.6-eclipse-temurin-17

stages:
  - test
  - deploy

run_tests:
  stage: test
  script:
    - echo "Iniciando testes automatizados..."
    - mvn clean test -Dmaven.test.failure.ignore=true
  artifacts:
    when: always
    paths:
      - allure-results
    reports:
      junit: target/surefire-reports/TEST-*.xml
    expire_in: 1 day
  allow_failure: true

pages:
  stage: deploy
  image: frankescobar/allure-docker-service
  script:
    - mkdir -p public
    - allure generate allure-results -o public --clean
  artifacts:
    paths:
      - public
    expire_in: 30 days
  needs:
    - run_tests
  rules:
    - if: $CI_COMMIT_BRANCH == "master"